algoritmo "verificar_se_o_número_é_maior_que_10"
// Função :Ler um valor e escrever a mensagem É MAIOR QUE 10!
// se o valor lido for maior que 10, caso contrário escrever NÃO É MAIOR QUE 10!
// Autor : Ila Carolina de Abreu Santos
// Data : 22/09/2020
// Seção de Declarações 
var
   n: inteiro
inicio
escreva("Digite um número: ")
leia(n)
       se (n > 10) entao
          escreva("É MAIOR QUE 10! ")
       senao
            escreva("NÃO É MAIOR QUE 10! ")
       fimse
fimalgoritmo
