algoritmo "verificar_se_o_número_é_positivo_ou_negativo"
// Função : Ler um valor e escrever se é positivo ou negativo.
// Autor : Ila Carolina de Abreu Santos
// Data : 22/09/2020
// Seção de Declarações 
var
   n: inteiro
inicio
escreva("Digite um número: ")
leia(n)
       se (n >= 0) entao
          escreva("O número digitado é POSITIVO ")
       senao
            escreva("O número digitado é NEGATIVO ")
       fimse
fimalgoritmo
