algoritmo "Estrutura condicional Se"
// Função :
// Autor : Ila Carolina de Abreu Santos
// Data : 08/09/2020
// Seção de Declarações 
var
ano, nasc, idade: inteiro
inicio
escreva("Em que ano estamos: ")
leia(ano)
escreva("Em que ano você nasceu: ")
leia(nasc)
idade<-ano-nasc
escreval("A sua idade é: ", idade)
se idade>=18 entao
escreval("Você pode tirar a sua habilitação")
senao
escreva("Você não pode tirar habilitação")
fimse
fimalgoritmo
