algoritmo "Soma de dois valores"
// Disciplina : Algoritmos e Programação Estruturada
// Função : Programa para somar dois valores
// Autor : Ila Carolina de Abreu Santos
// Data : 31/08/2020
// Seção de Declarações 
var
   V1, V2, R: inteiro
inicio
// Seção de Comandos 
   escreva("Digite o primeiro valor para a soma: ")
   leia(V1)
   escreva("Digite o segundo valor: ")
   leia(V2)
   R <- V1 + V2
   escreva("O resultado da soma entre os dois valores digitados é: ", R)
fimalgoritmo
